name: String Expansion CD

on:
  release:
    types: [ "published" ]

jobs:
  call-ci:
    uses: ./github/workflows/ci.yml

  publish:
    runs-on: ubuntu-latest

    needs: call-ci

    steps:

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Update package version
        run: sed -i "s/\"version\": \".*\",/\"version\": \"${github.event.release.tag_name}\",/" package.json

      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
